### ISSUE TITLE
BitBlt failed in windows server

### ISSUE THREAD

**Issue by uiosun** [vova616/screenshot#25]
When my focus is not in the remote connection, I get an error:

```bash
panic: BitBlt failed

	goroutine 1 [running]:
	click_modify/client.(*Client).saveImg(0x11e1a300?, 0x140, 0xa5, 0x384, 0x78, {0x7ff7bbf1515f, 0xd})
D:/Code/Go/click_modify/client/login.go:244 +0x3b9
	click_modify/client.(*Client).RefreshValueLogical(0xc000100180, {{0xc000098d40, 0xc}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x0, ...}})
D:/Code/Go/click_modify/client/refresh.go:72 +0x23a
	click_modify/client.(*Client).UserRefreshClient(0xc000100180, 0x10?)
D:/Code/Go/click_modify/client/refresh.go:21 +0xe5
	click_modify/client.(*Client).UserSetOrder(0xc000100180, 0xc000058180)
D:/Code/Go/click_modify/client/trade.go:74 +0x79d
	click_modify/client.(*Client).NewConnect(0xc000100180)
D:/Code/Go/click_modify/client/bootstrap.go:125 +0x870
	main.main()
D:/Code/Go/click_modify/client.go:48 +0x272
```

This my code:

```go
	// Define the screenshot area coordinates and dimensions
	rect := image.Rect(x, y, x+width, y+high)

	// Screen cut
	img, err := screenshot.CaptureRect(rect)
	if err != nil {
		fmt.Println("retry...")
		time.Sleep(1500 * time.Millisecond)
		img, err = screenshot.CaptureRect(rect)
		if err != nil {
			fmt.Println("retry failed.")
			panic(err)
		}
	}
```

**Comment by uiosun** [comment]
Ops, I use other package...

**Comment by Ostaer** [comment]
> Ops, I use other package...

Which package?
